CXX ?= g++
CXXSTD ?= c++20
CXXWARN ?= -O2 -Wall -Wextra -Wshadow -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op
CXXFLAGS := -std=$(CXXSTD) $(CXXWARN)
TARGET := main
SRC := main.cpp

.PHONY: all build clean test

all: build

build:
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

test: build
	$(ROOT)/test.sh

clean:
	rm -f $(TARGET) tests/*.out.tmp
